sudo: false
dist: trusty
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  browserstack:
    username: ${BROWSERSTACK_USER}
    access_key:
      secure: "kf4v23R4431/OjD+k48qe+PaYtUN/5t+hs57CGmYl7553WwOdAf08HdXEt75gr7+nOvNyu3aE82ZvjoPfXcAd2Ed7HvOwjtylQkLBdhhk40bt1T+exDUWwWzPH6XVE/Qs4vGmhLvvoW+aYLPpYmhycto+FLcTcbEr4rwDXQ8DUHfAXrBkMH4dnT3QHADrC+ELZnBIUyb7toGbwGWAkjsPJ2hC+uLi17HGVl1oo4+dNvKGsxkeoKKmkAyCY/sJKs4+XkW8oQATBmv/VLh28ZS9oyBQTX5qUn5uWFMMfm++tqwds2+kHuCMhZHV1WxdpeI9EWrlvVsq7dRiHGgWG+U2uxVl2lPCnPNkTENEAgfpkxmJzNOpimav0gEAVCVK4BLDVN/YsV1gnGNwyxeb2MnBtjwT0KqR1BJUiRKREbF0WIjc6ozXpI3anq+18QHIZI7Y3eRAVplSqr5kuw2vmKtIVl8SDm/sRqPaAtOkQQM+nF5N4y0DodCC0SAX32M3e1RU9rnKkSriI/9VQm4Oc63IUCc6TxO71ReVeqSFgZ+dPmq2VETd2aw1DpXEXDAiv6XTxOGiJ5NFoazE5ibWa23rAYx/s4UO3Kgq0hUPbhup2RGytjDTNYOWB9+yzN73++rBx+2+d5QPdZvd9KLRfo62pw/2Ae5W0MekEIo6zvqxYM="

services:
  - mysql

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - MAGENTO_DIRECTORY=${HOME}/magento
    - MAGENTO_VERSION=1.9.4.0
    - EXTENSION_NAME="wirecard-ee"
    - n98="php ${TRAVIS_BUILD_DIR}/n98-magerun.phar -n --root-dir=${MAGENTO_DIRECTORY}"
    - NGROK_SUBDOMAIN=c596a2a9
    - github_token:
        secure: "D4Kx568TZU1w8YPJ/yCCbJjNGvuOfJ/xhKTJ7mG2Yide4+OrDvoRw4KrQ6Eku68ceMNAnziEtGcPEauCoxAyrC4Dykvkq2tCXOZfg//Vaoj/VepNUfrmqVQe0OgZeBHlchvDUr/ygdBDGLQDJc3bF1+s0VHljiZCoRO/POLELiN7Wd2yNtELfH+LIRlO1E1VVz7yib8fgJeB3G6WL/klHj0nW5fzFRDvWN5fcCELWUA659wI7ehdhzaLKnNAc1uhZPTA2XDKqTU0Nsu5y3f58ugfcXFNtd7G1LCwrsTwrUYk/pXBUWMbeQSg8CIhgc65dZeWADkHiiEr0/CF1Vgu2yjexncTbAlnJYyqz9AO9LP4zMN3OGaqmOC0Kf9lhc5NVqVsjSQk2yYYSjGiTrjKZ2E2zIqyGS7C+JzAzcrAkfc92zH7+4OoPcicxQkfSXyUpcSW2yk9GUqCjG0H6YzHHudVUh9cCVCeXtPaxm6ePiboTc0DvIJea2qMob8Sb40/MxMOjlPsnu+1JCq6WwJLez2Evc8t0ZWujQYr4N2iHUmdHWRfOl9s/QdcrI3ispzEx3C5h46XIt0QzigY3cc7aLKbpGFSd7bGM/gYJepeOK1R2KY8EbNJ12/PHlLn26fw2fPa+ZxAKpscB1aDOV7plDWh1jVX1wi9KjFydJdcAIo="

matrix:
  allow_failures:
    - stage: acceptance-test
  include:
    - php: 5.6
      if: type != cron
    - php: 7.0
      if: type != cron
    - php: 7.1
      if: type != cron
    - php: 7.2
      if: type != cron
    - stage: acceptance-test
      if: type = cron
      php: 7.2
      env: GATEWAY=API-TEST
      before_script:
      - cd ${TRAVIS_BUILD_DIR}
      - travis_retry npm install
      # run UI tests
      script: travis_wait npm run test:runner
      after_script: skip
      after_failure:
      - bash ./build/bin/send-notify.sh


before_install:
  #get apache
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f build/bin/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%DOCUMENT_ROOT%?${MAGENTO_DIRECTORY}?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
  # get magento installed
  - wget https://files.magerun.net/n98-magerun.phar
  - $n98 --version
 # prepare database with sample data
  - mysql -e 'CREATE DATABASE magento;'
  - mysql -u travis magento < build/bin/magento_sample_data_for_1.9.2.4.sql


install:
  - travis_retry composer install $COMPOSER_ARGS
  #- travis_retry npm install
  - composer show
  # Download proper Magento version
  - git clone https://github.com/OpenMage/magento-mirror.git ${MAGENTO_DIRECTORY}
  - cd ${MAGENTO_DIRECTORY}
  - git tag -l
  - git checkout tags/${MAGENTO_VERSION}
  # Install Magento
  - $n98 sys:check
  - $n98 install --dbUser=travis --dbHost=127.0.0.1 --dbName=magento --baseUrl="http://127.0.0.1:8000" --installationFolder=${MAGENTO_DIRECTORY} --noDownload --forceUseDb
  - wget https://raw.github.com/colinmollenhour/modman/master/modman
  - chmod +x modman
  - ./modman init
  # Install the extension
  - cp -r ${TRAVIS_BUILD_DIR} ${MAGENTO_DIRECTORY}/.modman/${EXTENSION_NAME}
  - ./modman deploy ${EXTENSION_NAME}
  - cd ${MAGENTO_DIRECTORY}/.modman/${EXTENSION_NAME}
  # activate all payment methods
  - mysql -u travis magento < build/bin/payment_method_config.sql
  # activate symlinks so plugin is displayed in the shop
  - $n98 dev:symlinks 1


script:
  - composer cs-check
  - composer test-coverage
  - build/bin/find-sensitive-data


after_script:
  - travis_retry composer upload-coverage


after_failure:
  - cat ${MAGENTO_DIRECTORY}/var/log/wirecard_elastic_engine.log


notifications:
  email: false
  slack:
    rooms:
      secure: YI7sUrfMyKyJD60kElGkO7yBDkGEh+069yS8bFAIDUST7s48J+dDP/r2G9dN9oQwhs9hvNjpNytpZDPys838T+Z0mNtFZ9Wu022hV3MpbKUuMl7L9P0MQQmxjg4bKyKK3Hl9tPrZ3UsKRlwIUmRGGYQ7cjs4zumorqs19YsB3X+WnnxAmmYB3kHQYfNKgVnmcG2QHJyx5KaLZ0EsWynSHXkYb8bVCtdlbQFNnpChvGHPprZrHAszLCYnlU7AEZGdbuk17oIfXO9Wjuu1GV8iJ2VgKkTCzW4FBC5eHJyZezojPFUm1I5tvdihRZuyBekVGOF23J6pvHLqPx77clT+/Vn6T+UMDuh1INZ0LKt4UOU42oEDKGblWZx2VYWcHwfEK+ckJWZkT9EBfg/CMenJly2tbtBj6++XNvxgGEDn6XqKIEatcb7X/aiy4f8BPXa3/pzgZAlvzZbGGqHFNZPAlgcXBBXgbaC7VvMhvi6Z5AG5ylKzPS5GCD95ozPC+cGv0234TBJus5oZck4qNiT53IUQ7Ta+OGVB0Mea105VAoQI0I7YcgaqW6c4h2YTmnuuQsIzAwPOrJ5TAinj8Z8mZ9C11tEcNF3Pgy1tOoG/YLurhOJm7v1ebotRb/DIeSHU8RfNatnDSSky4YS6Y8k2pQthdC9m7m2f2mJYuGdLjlM=
    template:
      - "%{repository}#%{build_number} (%{branch} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    on_success: change
    on_failure: change
